### ISSUE TITLE
React 18

### ISSUE THREAD

**Issue by Djibdjib** [mother/react-files#42] opened 2022-10-30 12:04 UTC
Hi, when this package may be available for react 18 ?

Regards

**Comment by KevinRavasi** [comment] 2022-11-24 13:32
Any news on this?

**Comment by asabhaney** [comment] 2022-11-25 05:25
Hoping to address this next week

**Comment by karls4** [comment] 2023-02-01 16:03
Any update on this? 

Or can you provide a workaround on how I can get this plugin working on my react 18 app?

**Comment by asabhaney** [comment] 2023-02-03 21:16
Part of the problem is that the testing library we were using (enzyme) does not support React 18, so we have to rewrite the tests. That being said, I've pushed out primitive support for React 18 in #43 if you're feeling bold and want to try it out. If you do decide to try it out, note that it branches off `react-files` version 3, which is in alpha 3 at the moment. There are some breaking changes between v2 and v3, so I'd suggest taking a look at the demos in #32 for upgrade guidance.

I'll try to get #43 merged in to v3 in the next few days, and release alpa-4 which will support React 18.

**Comment by asabhaney** [comment] 2023-02-06 21:42
Fixed in `3.0.0-alpha.4`

**Closed by asabhaney** 2023-02-06 21:42 UTC
